package bz.berufsschule.verzweigungen;

import javax.swing.*;
import java.util.Random;

public class random_emilio {
    public static void main(String[] args) {
        double media1;
        double media2;

        Random generatore = new Random();
        //Con la classe Random è possibile generare numeri casuali in modo semplice e veloce.
        //Con questo comando viene creato un generatore di numeri casuali.
        //Formula generale per i numeri casuali di un certo intervallo: int numero_n = generatore.nextInt(max-min+1)+min;
        int numero_n = generatore.nextInt(8)+12;

        if(numero_n == 12){
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12;
            media2 = media1/12;
            System.out.println("La media e " + media2);
        }
        else if (numero_n == 13) {
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            String input13 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero13 = Double.parseDouble(input13);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13;
            media2 = media1/13;
            System.out.println("La media e " + media2);
        } else if (numero_n == 14) {
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            String input13 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero13 = Double.parseDouble(input13);
            String input14 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero14 = Double.parseDouble(input14);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13 + numero14;
            media2 = media1/14;
            System.out.println("La media e " + media2);
        }
        else if (numero_n == 15) {
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            String input13 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero13 = Double.parseDouble(input13);
            String input14 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero14 = Double.parseDouble(input14);
            String input15 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero15 = Double.parseDouble(input15);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13 + numero14 + numero15;
            media2 = media1/15;
            System.out.println("La media e " + media2);
        }
        else if (numero_n == 16) {
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            String input13 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero13 = Double.parseDouble(input13);
            String input14 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero14 = Double.parseDouble(input14);
            String input15 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero15 = Double.parseDouble(input15);
            String input16 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero16 = Double.parseDouble(input16);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13 + numero14 + numero15 + numero16;
            media2 = media1/16;
            System.out.println("La media e " + media2);
        }
        else if (numero_n == 17) {
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            String input13 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero13 = Double.parseDouble(input13);
            String input14 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero14 = Double.parseDouble(input14);
            String input15 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero15 = Double.parseDouble(input15);
            String input16 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero16 = Double.parseDouble(input16);
            String input17 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero17 = Double.parseDouble(input17);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13 + numero14 + numero15 + numero16 + numero17;
            media2 = media1/17;
            System.out.println("La media e " + media2);
        }
        else if (numero_n == 18) {
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            String input13 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero13 = Double.parseDouble(input13);
            String input14 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero14 = Double.parseDouble(input14);
            String input15 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero15 = Double.parseDouble(input15);
            String input16 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero16 = Double.parseDouble(input16);
            String input17 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero17 = Double.parseDouble(input17);
            String input18 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero18 = Double.parseDouble(input18);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13 + numero14 + numero15 + numero16 + numero17 + numero18;
            media2 = media1/18;
            System.out.println("La media e " + media2);
        }
        else if (numero_n == 19) {
            System.out.println(numero_n);
            String input1 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero1 = Double.parseDouble(input1);
            String input2 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero2 = Double.parseDouble(input2);
            String input3 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero3 = Double.parseDouble(input3);
            String input4 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero4 = Double.parseDouble(input4);
            String input5 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero5 = Double.parseDouble(input5);
            String input6 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero6 = Double.parseDouble(input6);
            String input7 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero7 = Double.parseDouble(input7);
            String input8 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero8 = Double.parseDouble(input8);
            String input9 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero9 = Double.parseDouble(input9);
            String input10 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero10 = Double.parseDouble(input10);
            String input11 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero11 = Double.parseDouble(input11);
            String input12 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero12 = Double.parseDouble(input12);
            String input13 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero13 = Double.parseDouble(input13);
            String input14 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero14 = Double.parseDouble(input14);
            String input15 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero15 = Double.parseDouble(input15);
            String input16 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero16 = Double.parseDouble(input16);
            String input17 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero17 = Double.parseDouble(input17);
            String input18 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero18 = Double.parseDouble(input18);
            String input19 = JOptionPane.showInputDialog("Inserisci un numero:");
            double numero19 = Double.parseDouble(input19);
            media1 = numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13 + numero14 + numero15 + numero16 + numero17 + numero18 + numero19;
            media2 = media1/19;
            System.out.println("La media e " + media2);
        }

    }
}
